### PR TITLE
Update Windows Icon

### PR DESCRIPTION
**Pull request by LordNyriox**
I converted the modern Mac/Linux icons to fit the Windows icon format, replacing the icon from the ancient "Ideas From the Deep" port. In compliance with [Bugdom.exe.rc#L11](https://github.com/jorio/Bugdom/blob/d4b5e729cf6747f1b07ee2752c824ac882f5ce5b/packaging/Bugdom.exe.rc#L11), all embedded size layers are without PNG compression.

Icon layers scaled using @bricelam's [ImageResizer 3.1.2](https://github.com/bricelam/ImageResizer/releases/tag/v3.1.2), then combined into an ICO file using [GIMP 2.10.32](https://www.gimp.org/downloads/).

Size Layers: { 256x256 (32-bit color), 48x48 (32-bit color), 32x32 (original indexed icon) }

### CODE REVIEW

**Comment by jorio** [comment]
Thank you for your PR and for taking the time to research how to correctly generate the icon!

I'd like to keep the old 32x32 icon because I like the idea of preserving the OS 9 icon on at least one of the target platforms. However, adding a hi-res icon in addition to the old-school icon is a good idea.

To keep the file under 300 KB, I suggest keeping just 32x32 (indexed-color original), 48x48 (your rescaled version) and 256x256. Windows 10 will downscale the 256x256 icon as needed for sizes larger than 48.

**Comment by LordNyriox** [comment]
> Windows 10 will downscale the 256x256 icon as needed for sizes larger than 48.
In my experience, Windows scales icons much more smoothly if it has a wider range of sizes to start from (which is why I embed so many sizes in my icons in the first place).  That being said, I do understand the desire to keep file-sizes low. 

> To keep the file under 300 KB, I suggest keeping just 32x32 (indexed-color original), 48x48 (your rescaled version) and 256x256. 
Icon built and soon to be uploaded.  Fair warning, I only use the browser interface of Github (not the `git` command-line tools), so I cannot squash the commits in the PR branch.

**Comment by LordNyriox** [comment]
> Windows 10 will downscale the 256x256 icon as needed for sizes larger than 48.

In my experience, Windows scales icons much more smoothly if it has a wider range of sizes to start from (which is why I embed so many sizes in my icons in the first place).  That being said, I do understand the desire to keep file-sizes low. 

> To keep the file under 300 KB, I suggest keeping just 32x32 (indexed-color original), 48x48 (your rescaled version) and 256x256. 

Icon built and soon to be uploaded.  Fair warning, I only use the browser interface of Github (not the `git` command-line tools), so I cannot squash the commits in the PR branch.

**Comment by LordNyriox** [comment]
> Windows 10 will downscale the 256x256 icon as needed for sizes larger than 48.

In my experience, Windows scales icons poorly unless it has a wide range of baked-in sizes to scale from (which is why I embed so many size layers in my icons in the first place).  That being said, I do understand the desire to keep file sizes low. 

> To keep the file under 300 KB, I suggest keeping just 32x32 (indexed-color original), 48x48 (your rescaled version) and 256x256. 

**Icon built and uploaded.**  Fair warning, I only use the browser interface of Github, so I cannot `squash` the commits in the PR branch.

**Comment by jorio** [comment]
Np, I'll squash it myself when I'm ready to merge. Thanks!

**Comment by LordNyriox** [comment]
@jorio: Off-topic, I am working on a "modernized" fork of *Bugdom*, and could use some technical advice on the code.

Would it be be alright for me to Bugdom code questions in [<https://github.com/jorio/Bugdom/issues/24>], since implementing that issue is where I started my fork?

**Comment by LordNyriox** [comment]
@jorio: Off-topic, I am working on a "modernized" fork of *Bugdom*, and could use some technical advice on the code.

Would it be be alright for me to post Bugdom code questions in [<https://github.com/jorio/Bugdom/issues/24>], since implementing that issue is where I started my fork?

**Comment by jorio** [comment]
Sure! I'll be happy to help. You can also contact me directly if you wish (email address in my profile).

**Comment by jorio** [comment]
@LordNyriox, I think this PR got automatically closed when you recreated your repo before I got a chance to merge it. I can re-add the icon manually, or you can submit a new PR if you like.

**Comment by LordNyriox** [comment]
@jorio: 

> I can re-add the icon manually 

I honestly forgot about this PR until *after* I had already reset my forked repository. 

Feel free to manually rebase or merge the icon commit as you wish. 😄

**Pull request closed without merging**
